#!/bin/bash

printf "==================================================\n"
printf "Debian Basic paket installation & configuration!\n"
printf "==================================================\n"

print "Do you want to start? [y/n]: "
read CHAR_DESISSION

if [$CHAR_DESISSION -eq "y"]; then
  if ["$(id -u)" -eq "0"]; then
    printf "Modify .bashrc for root user ..."
    echo "\n\n" >> ~/.bashrc
    echo "====================\nCustom Config\n===================\n" >> ~/.bashrc
    echo "force_color_prompt=yes" >> ~/.bashrc
    echo "HISTCONTROL=ignoreboth" >> ~/.bashrc
    echo "HISTSIZE=1000" >> ~/.bashrc
    echo "HISTFILESIZE=2000" >> ~/.bashrc
    echo "shopt -s histappend" >> ~/.bashrc
    echo "shopt -s checkwinsize" >> ~/.bashrc
    echo "PS1='\[\033[01;31m\][\[\033[01;33m\]\t\[\033[01;31m\]]─[\[\033[01;31m\]\u\[\033[01;33m\]@\[\033[01;96m\]\h\[\033[01;31m\]]─[\[\033[0;32m\]\w\[\033[01;31m\]]\[\033[38;5;15m\]\n\[\033[01;31m\]\\$\[\033[01;33m\]: \[\033[0;92m\]'" >> ~/.bashrc
    echo "export OPTIONS='--color=auto'" >> ~/.bashrc
    echo "eval \"`dircolors`\"" >> ~/.bashrc
    echo "alias ls='ls $OPTIONS'" >> ~/.bashrc
    echo "alias grep='grep $OPTIONS'" >> ~/.bashrc

    printf "Updating Repositories ..."
    apt get update > /var/log/script_stdout.log 2> /var/log/script_error.log &

    printf "Installing basic packets ..."
    apt install -qq apt-transport-https > /var/log/script_stdout.log 2> /var/log/script_error.log &
    apt install -qq ca-certificates > /var/log/script_stdout.log 2> /var/log/script_error.log &
    apt install -qq curl > /var/log/script_stdout.log 2> /var/log/script_error.log &
    apt install -qq htop > /var/log/script_stdout.log 2> /var/log/script_error.log &
    apt install -qq net-tools > /var/log/script_stdout.log 2> /var/log/script_error.log &
    apt install -qq open-ssh-server > /var/log/script_stdout.log 2> /var/log/script_error.log &

    printf "Configuring SSH-Server ..."
    printf "Which port do you want to use? [1025-65535]: "
    read INT_SSHPORT

    while [ $INT_SSHPORT -gt 65535 ] || [ $INT_SSHPORT -lt 1025 ]; do
      printf "Port not in Range [1025-65535]!"
      printf "Which port do you want to use? [1025-65535]: "
      read INT_SSHPORT
    done

    printf "Setting up SSH-Server ..."
    if [ $INT_SSHPORT -ge 1025 ] && [ $INT_SSHPORT -le 65535 ]; then
      echo -e "\n\n=======================\nCustom Config\n=======================\n" >> /etc/ssh/sshd_config
      echo -e "Port $INT_SSHPORT" >> /etc/ssh/sshd_config
      echo -e "LoginGracetime 30" >> /etc/ssh/sshd_config
      echo -e "PermitRootLogin no" >> /etc/ssh/sshd_config
      echo -e "StrictModes yes" >> /etc/ssh/sshd_config
      echo -e "MaxAuthTries 3" >> /etc/ssh/sshd_config
      echo -e "MaxSessions 3" >> /etc/ssh/sshd_config
    fi

  else
    printf "Coloring prompt for non-root users ..."
    echo "\n\n" >> ~/.bashrc
    echo "====================\nCustom Config\n===================\n" >> ~/.bashrc
    echo "PS1='\[\033[01;31m\][\[\033[01;33m\]\t\[\033[01;31m\]]─[\[\033[0;92m\]\u\[\033[01;33m\]@\[\033[01;96m\]\h\[\033[01;31m\]]─[\[\033[0;32m\]\w\[\033[01;31m\]]\[\033[38;5;15m\]\n\[\033[01;31m\]\\$\[\033[01;33m\]: \[\033[0;92m\]'" >> ~/.bashrc
  fi
else
  printf "OK! See you soon :)\n"
fi